### PR TITLE
This code makes sure that when the user tries to autologin when the token is expired, it will delete  the token and return null.

### PR DESCRIPTION
**Pull request by stealthAngel**
@watson\autologin\src\Autologin.php

### New function added autologinTokenIsExpired()
 /**
     * Checks if the autologin token date is expired.
     *
     * @param  string  $date
     * @return bool
     */
```
    protected function autologinTokenIsExpired($date)
    {
        $lifetime = config('autologin.lifetime');

        return ( $date <= Carbon::now()->subMinutes($lifetime));
    }
```
### Edited validate() function
/**
     * Validate a token from storage and return the row.
     *
     * @param  string  $token
     * @return mixed
     */

```
   public function validate($token)
    {
        $autologin = $this->provider->findByToken($token);

        if ($autologin) {

            if (config('autologin.remove_expired')){

                if($this->autologinTokenIsExpired($autologin->created_at))
                {
                    $autologin->delete();

                    return null;
                }
            }

            if (config('autologin.count')) {
                $autologin->incrementCount();
            }

            return $autologin;
        }

        return null;
    }
```

### CODE REVIEW

**Comment by dwightwatson** [comment]
You're trying to merge the latest version into the `0.2` branch. `0.2` tracks an older version of the package and `master` tracks the current version. Please just use the current version of the package.

**Comment by stealthAngel** [comment]
"Please just use the current version of the package."

Do you mean I should wait till an update comes or I should pull request somewhere else?

The auto login links are still available despite you giving time at config/autologin.php

**Comment by dwightwatson** [comment]
Use the current version, `0.5.2`.

If there is a bug in it I'm more than happy to accept a fix but this PR does not contain any code from you - it's just merging one branch into another.

**Comment by stealthAngel** [comment]
That's nice.

Can you fix that when a user wants to autologin when the date is expired that the link redirects back to somewhere? //although I have made it :(

**Comment by dwightwatson** [comment]
If you can make a PR for it I'll gladly look it over, otherwise please open an issue for it and I will try and find some time to implement it.

**Comment by stealthAngel** [comment]
Thank you for your answer. I gladly want to do it but I can't make any pull request for the master branch.

I can only make pull requests for branch 0.2 and branch "fix/broken"

**Pull request closed without merging**
